### ISSUE TITLE
Question about community.digitalocean.digital_ocean_droplet and wait (to get IP)

### ISSUE THREAD

**Issue by fey** [ansible-collections/community.digitalocean#116]
##### SUMMARY
```yaml
    - name: Create a new droplets
      register: droplets_data
      community.digitalocean.digital_ocean_droplet:
        state: present
        wait: yes
        name: "{{ item.name }}"
        unique_name: yes # "yes" makes it idempotent
        wait_timeout: 500
        # oauth_token: "{{ do_api_key }}" # use DO_API_TOKEN env var
        size: s-1vcpu-1gb # cheapest
        region: ams3
        image: docker-20-04
        ssh_keys:
          - "{{ do_ssh_key.data.0.id }}"
      with_items:
        - name: as-a-code-homework-01
        - name: as-a-code-homework-02
```

Hello, i use `wait` in my tasks to get IP address but it always return response  immediately, so registered variable does not have ip of droplet.
How to get ip address from creating droplet tasks?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
module community.digitalocean.digital_ocean_droplet

##### ANSIBLE VERSION
```sh
ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/feycot/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]

```
