### ISSUE TITLE
digital_ocean_firewall - no idempotence

### ISSUE THREAD

**Issue by nickerejv** [ansible-collections/community.digitalocean#122]
##### SUMMARY
I have just applied a very simple firewall rule, basically from the sample documentation. When re-executing the playbook I keep getting changed result from the task. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.digitalocean.digital_ocean_firewall

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.1] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nickep/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/nickep/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.5 (default, May 24 2021, 12:50:35) [GCC 11.1.0]
  jinja version = 3.0.1
  libyaml = True

```

##### COLLECTION VERSION

```paste below
# /home/user/.ansible/collections/ansible_collections
Collection             Version
---------------------- -------
community.digitalocean 1.7.0  


```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
    - name: Create a Firewall named my-firewall
      community.digitalocean.digital_ocean_firewall:
        name: my-firewall
        state: present
        oauth_token: "{{ digital_ocean_token }}"
        inbound_rules:
          - protocol: "tcp"
            ports: "22"
            sources:
              addresses: "my ip in the correct format"

          - protocol: "tcp"
            ports: "80"
            sources:
              addresses: ["0.0.0.0/0", "::/0"]

          - protocol: "tcp"
            ports: "443"
            sources:
              addresses: ["0.0.0.0/0", "::/0"]

        outbound_rules:
          - protocol: "tcp"
            ports: "1-65535"
            destinations:
              addresses: ["0.0.0.0/0", "::/0"]

          - protocol: "udp"
            ports: "1-65535"
            destinations:
              addresses: ["0.0.0.0/0", "::/0"]

          - protocol: "icmp"
            ports: "1-65535"
            destinations:
              addresses: ["0.0.0.0/0", "::/0"]
        droplet_ids: "{{ my_droplet.data.droplet.id }}"



```

##### EXPECTED RESULTS

Getting the text "OK" instead of change on consecutive re executing of the task.

##### ACTUAL RESULTS

TASK [Create a Firewall named my-firewall] ***************************************************************************************************************
changed: [localhost] => {"changed": true, "data": {"created_at": "2021-06-30T20:56:12Z", "droplet_ids": [251993461], "id": "292a359d-303c-49a8-897b-0b4149aa43f6", "inbound_rules": [{"ports": "22", "protocol": "tcp", "sources": {"addresses": ["62.63.220.246"]}}, {"ports": "80", "protocol": "tcp", "sources": {"addresses": ["0.0.0.0/0", "::/0"]}}, {"ports": "443", "protocol": "tcp", "sources": {"addresses": ["0.0.0.0/0", "::/0"]}}], "name": "my-firewall", "outbound_rules": [{"destinations": {"addresses": ["0.0.0.0/0", "::/0"]}, "ports": "1-65535", "protocol": "icmp"}, {"destinations": {"addresses": ["0.0.0.0/0", "::/0"]}, "ports": "1-65535", "protocol": "tcp"}, {"destinations": {"addresses": ["0.0.0.0/0", "::/0"]}, "ports": "1-65535", "protocol": "udp"}], "pending_changes": [], "status": "succeeded", "tags": []}}

hanged: [localhost] => {
    "changed": true,
    "data": {
        "created_at": "2021-06-30T20:34:49Z",
        "droplet_ids": [
            251993461
        ],
        "id": "ae037cd2-6a64-4138-b902-e567054c8893",
        "inbound_rules": [
            {
                "ports": "22",
                "protocol": "tcp",
                "sources": {
                    "addresses": [
                        "62.63.220.246"
                    ]
                }
            },
            {
                "ports": "80",
                "protocol": "tcp",
                "sources": {
                    "addresses": [
                        "0.0.0.0/0",
                        "::/0"
                    ]
                }
            },
            {
                "ports": "443",
                "protocol": "tcp",
                "sources": {
                    "addresses": [
                        "0.0.0.0/0",
                        "::/0"
                    ]
                }
            }
        ],
        "name": "my-firewall",
        "outbound_rules": [
            {
                "destinations": {
                    "addresses": [
                        "0.0.0.0/0",
                        "::/0"
                    ]
                },
                "ports": "1-65535",
                "protocol": "icmp"
            },
            {
                "destinations": {
                    "addresses": [
                        "0.0.0.0/0",
                        "::/0"
                    ]
                },
                "ports": "1-65535",
                "protocol": "tcp"
            },
            {
                "destinations": {
                    "addresses": [
                        "0.0.0.0/0",
                        "::/0"
                    ]
                },
                "ports": "1-65535",
                "protocol": "udp"
            }
        ],
        "pending_changes": [],
        "status": "succeeded",
        "tags": []
    },
    "invocation": {
        "module_args": {
            "droplet_ids": [
                "251993461"
            ],
            "inbound_rules": [
                {
                    "ports": "22",
                    "protocol": "tcp",
                    "sources": {
                        "addresses": [
                            "62.63.220.246"
                        ],
                        "droplet_ids": [],
                        "load_balancer_uids": [],
                        "tags": []
                    }
                },
                {
                    "ports": "80",
                    "protocol": "tcp",
                    "sources": {
                        "addresses": [
                            "0.0.0.0/0",
                            "::/0"
                        ],
                        "droplet_ids": [],
                        "load_balancer_uids": [],
                        "tags": []
                    }
                },
                {
                    "ports": "443",
                    "protocol": "tcp",
                    "sources": {
                        "addresses": [
                            "0.0.0.0/0",
                            "::/0"
                        ],
                        "droplet_ids": [],
                        "load_balancer_uids": [],
                        "tags": []
                    }
                }
            ],
            "name": "my-firewall",
            "oauth_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "outbound_rules": [
                {
                    "destinations": {
                        "addresses": [
                            "0.0.0.0/0",
                            "::/0"
                        ],
                        "droplet_ids": [],
                        "load_balancer_uids": [],
                        "tags": []
                    },
                    "ports": "1-65535",
                    "protocol": "tcp"
                },
                {
                    "destinations": {
                        "addresses": [
                            "0.0.0.0/0",
                            "::/0"
                        ],
                        "droplet_ids": [],
                        "load_balancer_uids": [],
                        "tags": []
                    },
                    "ports": "1-65535",
                    "protocol": "udp"
                },
                {
                    "destinations": {
                        "addresses": [
                            "0.0.0.0/0",
                            "::/0"
                        ],
                        "droplet_ids": [],
                        "load_balancer_uids": [],
                        "tags": []
                    },
                    "ports": "1-65535",
                    "protocol": "icmp"
                }
            ],
            "state": "present",
            "tags": null,
            "timeout": 30,
            "validate_certs": true
        }
    }
}

```paste below

```
