### ISSUE TITLE
MongoDB missing from community.digitalocean.digital_ocean_database

### ISSUE THREAD

**Issue by JamesSc0tt** [ansible-collections/community.digitalocean#124]
##### SUMMARY
DigitalOcean released their MongoDB managed database clusters, which are available via the API with the name/slug 'mongodb', an example API call is below:

curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" -d '{"name": "backend", "engine": "mongodb", "version": "4", "region": "nyc3", "size": "db-s-1vcpu-1gb", "num_nodes": 1, "tags": ["production"]}'
 "https://api.digitalocean.com/v2/databases"

{"database":{"id":"1d897187-4608-42af-ad49-2565a8b5cf33","name":"backend","engine":"mongodb","version":"4","connection":{"protocol":"mongodb+srv","uri":"mongodb+srv://doadmin:XXXXXXXXXX@backend-6ee199d1.mongo.ondigitalocean.com/admin?tls=true&authSource=admin","database":"admin","host":"backend-6ee199d1.mongo.ondigitalocean.com","port":27017,"user":"doadmin","password":"XXXXXXXX","ssl":true},"private_connection":{"protocol":"mongodb+srv","uri":"mongodb+srv://doadmin:XXXXXXXX@private-backend-e9fdad2c.mongo.ondigitalocean.com/admin?tls=true&authSource=admin","database":"admin","host":"private-backend-e9fdad2c.mongo.ondigitalocean.com","port":27017,"user":"doadmin","password":"XXXXXXXXXX","ssl":true},"users":null,"db_names":null,"num_nodes":1,"region":"nyc3","status":"creating","created_at":"2021-07-02T10:24:13Z","maintenance_window":{"day":"","hour":"","pending":false},"size":"db-s-1vcpu-1gb","tags":["production"]}}

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.digitalocean.digital_ocean_database

##### ANSIBLE VERSION
```
ansible [core 2.11.2]
  config file = /Users/admin/Work/evamo-staging/setup/ansible.cfg
  configured module search path = ['/Users/admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.1.0/libexec/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/admin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 03:33:11) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION
```
community.digitalocean        1.5.1
```

##### CONFIGURATION
```paste below
No special configuration.
```

##### OS / ENVIRONMENT

MacOS Cataline version 10.15.7

##### STEPS TO REPRODUCE
Run the digital_ocean_database to create a managed database cluster

```yaml
- name: Setup/DO | Create '{{ db_engine }}' Managed Cluster
      community.digitalocean.digital_ocean_database:
        region: "{{ host_region }}"
        oauth_token: "XXXXXXXXXXXXXXXXXX"
        state: present
        name: "{{ db_engine }}.{{ host_environment }}.{{ host_region }}.{{ host_suffix }}"
        engine: "{{ db_engine }}"
        num_nodes: "{{ nodes }}"
        size: "{{ db_size }}"
      register: database_cluster
```

##### EXPECTED RESULTS
Expected return as of https://docs.ansible.com/ansible/latest/collections/community/digitalocean/digital_ocean_database_module.html

##### ACTUAL RESULTS
```paste below
TASK [Setup/DO | Create 'mongodb' Managed Cluster] **********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of engine must be one of: pg, mysql, redis, got: mongodb"}
```
