### ISSUE TITLE
Droplet tags with "dashes" are being replaced by "underscores" in DO ansible dynamic inventory

### ISSUE THREAD

**Issue by dfradejas** [ansible-collections/community.digitalocean#133]
##### SUMMARY

Hi,
I am using digitalocean dynamic inventory plugin and I want to split my droplets with tags. These tags are for example "postgres-master" or "postgres-slave", so my ansible playbooks are created with these selectors.

When i am using dynamic inventory and I split my hosts by tags (using this configuration)
```
---
plugin: community.digitalocean.digitalocean
attributes:
  - name
  - networks
  - tags
  - region
keyed_groups:
  - key: do_tags | lower
    prefix: ''
    separator: ''
replace_dash_in_groups: False
compose:
  ansible_host: do_networks.v4 | selectattr('type','eq','public')
    | map(attribute='ip_address') | first
filters:
  - '"QA" in do_tags'
  - 'do_region.slug == "fra1"'
  - '"es" in do_tags'
```
i cannot see "postgres-master" tag, it is replaced by "postgres_master". So, dashes are being replaced by "_" when I retrieve my inventory from DO.

I need to use "dashes". Are there any feature to do that?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.digitalocean.digitalocean – DigitalOcean Inventory Plugin

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.0] 
  config file = None
  configured module search path = ['/home/dfradejas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dfradejas/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/dfradejas/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/dfradejas/.local/bin/ansible
  python version = 3.9.6 (default, Jul 16 2021, 00:00:00) [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/dfradejas/.local/lib/python3.9/site-packages/ansible_collections
Collection             Version
---------------------- -------
community.digitalocean 1.1.1  

# /home/dfradejas/.ansible/collections/ansible_collections
Collection             Version
---------------------- -------
community.digitalocean 1.7.0
```

##### STEPS TO REPRODUCE

* Create droplet with "postgres-master" tag.
* Configure do_hosts.yml file (explained in summary)
* Retrieve inventory `ansible-inventory -i do_hosts.yml --list`

##### EXPECTED RESULTS

I expect to get "postgres-master" host group and not "postgres_master"

##### ACTUAL RESULTS

Droplet tags:
![image](https://user-images.githubusercontent.com/38228474/126742097-5259dfdd-f83e-4058-a0bb-52cbef5a75c2.png)
Command results:
```
$ ansible-inventory -i do_hosts.yml --list
{
    "all": {
        "children": [
            "es",
            "postgres_master",
            "qa",
            "ungrouped"
        ]
    },
    "es": {
        "hosts": [
            "activemq"
        ]
    },
    "postgres_master": {
        "hosts": [
            "activemq"
        ]
    },
    "qa": {
        "hosts": [
            "activemq"
        ]
    }
}
```
