### ISSUE TITLE
Resizing with 'state: active' doesn't actually turn the droplet on.

### ISSUE THREAD

**Issue by GoMatrixHosting** [ansible-collections/community.digitalocean#140]
##### SUMMARY
Using the droplet module to resize a droplet with 'state: active' doesn't actually turn that droplet on afterwards.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.digitalocean.digital_ocean_droplet

##### ANSIBLE VERSION

```
ansible 2.9.20
```

##### COLLECTION VERSION

```
community.digitalocean v1.8.0
```

##### CONFIGURATION

```
```

##### OS / ENVIRONMENT
Debian 10
AWX 17.0.1 

##### STEPS TO REPRODUCE

The following code should turn off the droplet, then resize it, then turn it back on:
```
- name: Spawn a new Digital Ocean Droplet, collect the IPv4+IPv6 addresses, then turn it off
  delegate_to: 127.0.0.1
  community.digitalocean.digital_ocean_droplet:
    state: inactive
    name: '{{ matrix_domain }}'
    oauth_token: '{{ do_api_token }}'
    size: '{{ slug_size }}'
    ssh_keys: '{{ ssh_key_id_array }}'
    region: '{{ do_droplet_region }}'
    image: '{{ do_image }}'
    ipv6: yes
    wait: yes
    unique_name: yes
  register: new_server_info
  when: subscription_type == "digitalocean"

- name: Re-spawn the Droplet, re-size it if needed, then turn it on
  delegate_to: 127.0.0.1
  community.digitalocean.digital_ocean_droplet:
    state: active
    name: '{{ matrix_domain }}'
    oauth_token: '{{ do_api_token }}'
    size: '{{ new_slug_size }}'
    ssh_keys: '{{ ssh_key_id_array }}'
    region: '{{ do_droplet_region }}'
    image: '{{ do_image }}'
    resize_disk: yes
    ipv6: yes
    wait: yes
    unique_name: yes
  when: subscription_type == "digitalocean"
```

##### EXPECTED RESULTS

The 'state: active' leaves the droplet turned on after the second task is done executing.

##### ACTUAL RESULTS

The droplet remains turned off after being resized, despite having 'state: active' set.
