### ISSUE TITLE
DigitalOcean Block Storage Not Idempotent (when detaching)

### ISSUE THREAD

**Issue by lucasbasquerotto** [ansible-collections/community.digitalocean#149]
##### SUMMARY
The DigitalOcean Block Storage module is NOT idempotent when detaching (creating, destroying and attaching are idempotent).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
digital_ocean_block_storage

##### ANSIBLE VERSION
```paste below
ansible [core 2.11.3] 
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection             Version
---------------------- -------
community.digitalocean 1.8.0 
```

##### CONFIGURATION

```paste below

```

*(no output)*

##### OS / ENVIRONMENT
Ubuntu 20.04 in a Docker Containe running inside WSL2 (Ubuntu 20.04 image, Windows10 host)

##### STEPS TO REPRODUCE
```yaml
# idempotent
- community.digitalocean.digital_ocean_block_storage:
    command: create
    state: present
    oauth_token: "API_KEY"
    volume_name: vol01
    region: ams3
    block_size: 10

# idempotent
- community.digitalocean.digital_ocean_block_storage:
    command: create
    state: absent
    oauth_token: "API_KEY"
    volume_name: vol01
    region: ams3

# idempotent
- community.digitalocean.digital_ocean_block_storage:
    command: attach
    state: present
    oauth_token: "API_KEY"
    volume_name: vol01
    region: ams3
    droplet_id: "droplet1"

# NOT idempotent
# after 1st time:
# error detaching volume from droplet: volume is not attached to droplet
- community.digitalocean.digital_ocean_block_storage:
    command: attach
    state: absent
    oauth_token: "API_KEY"
    volume_name: vol01
    region: ams3
    droplet_id: "droplet1"
```

##### EXPECTED RESULTS
Each command should be able to be executed in isolation several times consecutively without errors.

##### ACTUAL RESULTS
The last example (detaching a volume from a droplet) works only the first time, giving the error `error detaching volume from droplet: volume is not attached to droplet` from the 2nd time it runs onward, making the module not idempotent.
