### ISSUE TITLE
AttributeError: module object has no attribute monotonic in digital_ocean_droplet.py

### ISSUE THREAD

**Issue by sgpinkus** [ansible-collections/community.digitalocean#153]
##### SUMMARY
Get the following sometimes but not all the time (excuse the pun). The reason is `time.monotonic()` is not [Python 2.7](https://docs.python.org/2.7/library/time.html#module-time). Isn't ansible supposed to be 2.7 compatible?

```
Traceback (most recent call last):
  File \"<stdin>\", line 102, in <module>
  File \"<stdin>\", line 94, in _ansiballz_main
  File \"<stdin>\", line 40, in invoke_module
  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module
    fname, loader, pkg_name)
  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code
    exec code in run_globals
  File \"/tmp/ansible_community.digitalocean.digital_ocean_droplet_payload_EjvqnI/ansible_community.digitalocean.digital_ocean_droplet_payload.zip/ansible_collections/community/digitalocean/plugins/modules/digital_ocean_droplet.py\", line 558, in <module>
  File \"/tmp/ansible_community.digitalocean.digital_ocean_droplet_payload_EjvqnI/ansible_community.digitalocean.digital_ocean_droplet_payload.zip/ansible_collections/community/digitalocean/plugins/modules/digital_ocean_droplet.py\", line 554, in main
  File \"/tmp/ansible_community.digitalocean.digital_ocean_droplet_payload_EjvqnI/ansible_community.digitalocean.digital_ocean_droplet_payload.zip/ansible_collections/community/digitalocean/plugins/modules/digital_ocean_droplet.py\", line 504, in core
  File \"/tmp/ansible_community.digitalocean.digital_ocean_droplet_payload_EjvqnI/ansible_community.digitalocean.digital_ocean_droplet_payload.zip/ansible_collections/community/digitalocean/plugins/modules/digital_ocean_droplet.py\", line 377, in create
  File \"/tmp/ansible_community.digitalocean.digital_ocean_droplet_payload_EjvqnI/ansible_community.digitalocean.digital_ocean_droplet_payload.zip/ansible_collections/community/digitalocean/plugins/modules/digital_ocean_droplet.py\", line 416, in ensure_power_on
AttributeError: module object has no attribute monotonic
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`plugins/modules/digital_ocean_droplet.py`

##### ANSIBLE VERSION

```paste below
ansible 2.9.16
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/sam', '/home/sam/Projects/ansible/library']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0
```

##### COLLECTION VERSION
```paste below
1.9.0.
```

##### OS / ENVIRONMENT

```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

##### STEPS TO REPRODUCE
```
      community.digitalocean.digital_ocean_droplet:
        state: "{{ state }}"
        oauth_token: "{{ do_api_token }}"
        name: "{{ ansible_host }}"
        unique_name: yes
        id: "{{ do_id | default(0) }}"
        size: s-1vcpu-1gb
        region: "{{ do_vpc_region }}"
        image: "{{ do_vpc_default_image }}"
        private_networking: yes
        vpc_uuid: "{{ do_vpc_uuid }}"
        wait_timeout: 500
        ssh_keys: [ "{{ do_vpc_key_id }}" ]
        tags: "{{ [ansible_host] + custom_tags | default([]) }}"
```
