### ISSUE TITLE
RFE: Add 'auto_scale' subparameters to 'node_pools' parameter in module 'digital_ocean_kubernetes'

### ISSUE THREAD

**Issue by leomakkinje** [ansible-collections/community.digitalocean#157]
##### SUMMARY

Add the option to configure [Cluster Autoscaling](https://docs.digitalocean.com/products/kubernetes/how-to/autoscale/) by adding the `auto_scale` subparameters to the `node_pools` parameter.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

digital_ocean_kubernetes

##### ADDITIONAL INFORMATION

This feature allows the configuration of a node pool's autoscaling option, making it possible to enable or disable autoscaling and to set the minimum and maximum number of nodes in the pool.

The required subparameters are:
- `auto_scale`
- `min_nodes`
- `max_nodes`

```yaml
- name: Create a new DigitalOcean Kubernetes cluster in New York 1
  community.digitalocean.digital_ocean_kubernetes:
    state: present
    oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
    name: hacktoberfest
    region: nyc1
    node_pools:
      - name: hacktoberfest-workers
        size: s-1vcpu-2gb
        count: 3
        auto_scale: true
        min_nodes: 2
        max_nodes: 5
    return_kubeconfig: yes
    wait_timeout: 600
    register: my_cluster
```
