### ISSUE TITLE
Droplet not set on given project name

### ISSUE THREAD

**Issue by habibimustafa** [ansible-collections/community.digitalocean#201]
##### SUMMARY
When creating a new droplet with a project name, the new droplet is not set on the given project name. Instead, the new droplet are set on the default project.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.digitalocean.digital_ocean_droplet

##### ANSIBLE VERSION
```
ansible 2.10.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/myusername/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/myusername/.local/lib/python3.9/site-packages/ansible
  executable location = /home/myusername/.local/bin/ansible
  python version = 3.9.7 (default, Aug 31 2021, 13:28:12) [GCC 11.1.0]
```

##### COLLECTION VERSION
```
Collection             Version
---------------------- -------
community.digitalocean 1.13.0 
```

##### CONFIGURATION
```
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/home/myusername/.ansible/collections', '/usr/share/ansible/collections']
```

##### OS / ENVIRONMENT
```
Operating System: Manjaro Linux 21.1.6 Pahvo                   
Kernel: Linux 5.13.19-2-MANJARO
```

##### STEPS TO REPRODUCE
```yaml
---
- hosts: local
  become: true
  
  vars:
    my_token: ...
    
  tasks:
    - name: 'Create a DigitalOcean Droplet'
      community.digitalocean.digital_ocean_droplet:
        oauth_token: "{{ my_token }}"        
        name: node-name-1
        project: Testing # or project_name: Testing
        state: present
        size: s-1vcpu-1gb
        image: ubuntu-18-04-x64
        region: sgp1
```

```
ansible-playbook -vv project.yml
```

##### EXPECTED RESULTS
A new droplet set on Testing project (checked on cloud.digitalocean.com manually)

##### ACTUAL RESULTS
A new droplet set on default project (checked on cloud.digitalocean.com manually)

**Comment by dschilling** [comment]
This bug appears to still be active. These are my versions: community.digitalocean 1.16.0, ansible 2.12.4, python 3.9.7.

**Comment by mamercad** [comment]
> This bug appears to still be active, regardless whether unique_name is true or false. These are my versions: community.digitalocean 1.16.0, ansible 2.12.4, python 3.9.7.

This is being run out of `1.18.0` ...

Here's the playbook I'm using:

```yaml
---
- name: droplet
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:

    - name: Create a new Droplet (and assign to Project "test-project")
      community.digitalocean.digital_ocean_droplet:
        state: present
        oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
        name: mydroplet
        size: s-1vcpu-2gb
        region: sfo3
        image: ubuntu-20-04-x64
        wait_timeout: 500
        ssh_keys: ["{{ lookup('ansible.builtin.env', 'DO_SSH_KEY_ID') }}"]
        project: test-project
      register: my_droplet
```

Here's the output:

```
❯ ANSIBLE_PYTHON_INTERPRETER=$(which python3) ansible-playbook -i localhost, -c local droplet.yml -v
Using /Users/mark/.ansible.cfg as config file
[WARNING]: running playbook inside collection community.digitalocean

PLAY [droplet] ****************************************************************************************

TASK [Create a new Droplet (and assign to Project "test-project")] ************************************
Tuesday 10 May 2022  19:24:01 -0400 (0:00:00.107)       0:00:00.107 *********** 
changed: [localhost] => changed=true 
  assign_status: assigned
  data:
    droplet:
      backup_ids: []
      created_at: '2022-05-10T23:24:05Z'
      disk: 50
      features:
      - droplet_agent
      id: 299242353
      image:
        created_at: '2022-04-18T19:18:08Z'
        description: Ubuntu 20.04 x86
        distribution: Ubuntu
        id: 106421232
        min_disk_size: 7
        name: 20.04 (LTS) x64
        public: true
        regions:
        - nyc3
        - nyc1
        - sfo1
        - nyc2
        - ams2
        - sgp1
        - lon1
        - ams3
        - fra1
        - tor1
        - sfo2
        - blr1
        - sfo3
        size_gigabytes: 0.62
        slug: ubuntu-20-04-x64
        status: available
        tags: []
        type: base
      kernel: null
      locked: false
      memory: 2048
      name: mydroplet
      networks:
        v4: []
        v6: []
      next_backup_window: null
      region:
        available: true
        features:
        - backups
        - ipv6
        - metadata
        - install_agent
        - storage
        - image_transfer
        name: San Francisco 3
        sizes:
        - s-1vcpu-1gb
        - s-1vcpu-1gb-amd
        - s-1vcpu-1gb-intel
        - s-1vcpu-2gb
        - s-1vcpu-2gb-amd
        - s-1vcpu-2gb-intel
        - s-2vcpu-2gb
        - s-2vcpu-2gb-amd
        - s-2vcpu-2gb-intel
        - s-2vcpu-4gb
        - s-2vcpu-4gb-amd
        - s-2vcpu-4gb-intel
        - s-4vcpu-8gb
        - c-2
        - c2-2vcpu-4gb
        - s-4vcpu-8gb-amd
        - s-4vcpu-8gb-intel
        - g-2vcpu-8gb
        - gd-2vcpu-8gb
        - s-8vcpu-16gb
        - m-2vcpu-16gb
        - c-4
        - c2-4vcpu-8gb
        - s-8vcpu-16gb-amd
        - s-8vcpu-16gb-intel
        - m3-2vcpu-16gb
        - g-4vcpu-16gb
        - so-2vcpu-16gb
        - m6-2vcpu-16gb
        - gd-4vcpu-16gb
        - so1_5-2vcpu-16gb
        - m-4vcpu-32gb
        - c-8
        - c2-8vcpu-16gb
        - m3-4vcpu-32gb
        - g-8vcpu-32gb
        - so-4vcpu-32gb
        - m6-4vcpu-32gb
        - gd-8vcpu-32gb
        - so1_5-4vcpu-32gb
        - m-8vcpu-64gb
        - c-16
        - c2-16vcpu-32gb
        - m3-8vcpu-64gb
        - g-16vcpu-64gb
        - so-8vcpu-64gb
        - m6-8vcpu-64gb
        - gd-16vcpu-64gb
        - so1_5-8vcpu-64gb
        - m-16vcpu-128gb
        - c-32
        - c2-32vcpu-64gb
        - m3-16vcpu-128gb
        - m-24vcpu-192gb
        - g-32vcpu-128gb
        - so-16vcpu-128gb
        - m6-16vcpu-128gb
        - gd-32vcpu-128gb
        - m3-24vcpu-192gb
        - g-40vcpu-160gb
        - so1_5-16vcpu-128gb
        - m-32vcpu-256gb
        - gd-40vcpu-160gb
        - so-24vcpu-192gb
        - m6-24vcpu-192gb
        - m3-32vcpu-256gb
        - so1_5-24vcpu-192gb
        - so-32vcpu-256gb
        - m6-32vcpu-256gb
        - so1_5-32vcpu-256gb
        slug: sfo3
      size:
        available: true
        description: Basic
        disk: 50
        memory: 2048
        price_hourly: 0.01488
        price_monthly: 10.0
        regions:
        - ams3
        - blr1
        - fra1
        - lon1
        - nyc1
        - nyc3
        - sfo3
        - sgp1
        - tor1
        slug: s-1vcpu-2gb
        transfer: 2.0
        vcpus: 1
      size_slug: s-1vcpu-2gb
      snapshot_ids: []
      status: new
      tags: []
      vcpus: 1
      volume_ids: []
  msg: Assigned do:droplet:299242353 to project test-project
  resources:
    assigned_at: '2022-05-10T23:24:06Z'
    links:
      self: https://api.digitalocean.com/v2/droplets/299242353
    status: assigned
    urn: do:droplet:299242353

PLAY RECAP ********************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Tuesday 10 May 2022  19:24:52 -0400 (0:00:50.494)       0:00:50.601 *********** 
=============================================================================== 
Create a new Droplet (and assign to Project "test-project") ----------------------------------- 50.49s
Playbook run took 0 days, 0 hours, 0 minutes, 50 seconds
```

Here's a screenshot of the Cloud console:

<img width="707" alt="image" src="https://user-images.githubusercontent.com/6192266/167740810-46d0def7-86ab-4a07-8d1d-5986331d8e88.png">
