### ISSUE TITLE
Firewall not set to new droplet

### ISSUE THREAD

**Issue by habibimustafa** [ansible-collections/community.digitalocean#202]
##### SUMMARY
When creating a new droplet with a firewall configuration, the new droplet still doesn't have a firewall.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.digitalocean.digital_ocean_droplet

##### ANSIBLE VERSION
```
ansible 2.10.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/myusername/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/myusername/.local/lib/python3.9/site-packages/ansible
  executable location = /home/myusername/.local/bin/ansible
  python version = 3.9.7 (default, Aug 31 2021, 13:28:12) [GCC 11.1.0]
```

##### COLLECTION VERSION
```
Collection             Version
---------------------- -------
community.digitalocean 1.13.0 
```

##### CONFIGURATION
```
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/home/myusername/.ansible/collections', '/usr/share/ansible/collections']
```

##### OS / ENVIRONMENT
```
Operating System: Manjaro Linux 21.1.6 Pahvo                   
Kernel: Linux 5.13.19-2-MANJARO
```

##### STEPS TO REPRODUCE
```yaml
---
- hosts: local
  become: true
  
  vars:
    my_token: ...
    
  tasks:
    - name: 'Create a DigitalOcean Droplet'
      community.digitalocean.digital_ocean_droplet:
        oauth_token: "{{ my_token }}"        
        name: node-name-1
        state: present
        size: s-1vcpu-1gb
        image: ubuntu-18-04-x64
        region: sgp1
        firewall:
          - web-server-fw
```

```
ansible-playbook -vv project.yml
```

##### EXPECTED RESULTS
a new droplet with 'web-server-fw' firewall created

##### ACTUAL RESULTS
a new droplet without any firewall created
