### ISSUE TITLE
networks ( both v4 and v6 ) in droplet.networks are empty

### ISSUE THREAD

**Issue by Lvl4Sword** [ansible-collections/community.digitalocean#220]
##### SUMMARY
When creating a droplet, there are no ipv4 or ipv6 addresses present.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.digitalocean

##### ANSIBLE VERSION
```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

##### COLLECTION VERSION

```paste below
ansible-galaxy collection list
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_RETRIES(/etc/ansible/ansible.cfg) = 10
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['timer']
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 300
```

##### OS / ENVIRONMENT

Ubuntu 20.04 LTS

##### STEPS TO REPRODUCE

1. Make a droplet
2. Notice the IP addresses are missing
3. ????

```yaml
- name: Create a new Droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
    name: mydroplet
    size: s-1vcpu-1gb
    region: sfo3
    image: ubuntu-20-04-x64
    wait_timeout: 500
    ssh_keys: [ .... ]
  register: my_droplet
```

##### EXPECTED RESULTS

IP addresses are present

##### ACTUAL RESULTS

They are not present

```paste below

```

**Comment by mamercad** [comment]
Looks like the module isn't waiting long enough, or polling correctly -- I've tried this with state `active` as well. In the mean time, as a workaround, you could use something like:

```
- name: Wait for a minute
  ansible.builtin.pause:
    minutes: 1

- name: Get Droplet Info
  community.digitalocean.digital_ocean_droplet_info:
    oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
    name: mydroplet
  register: my_droplet_info
```

...after your creation play.

**Comment by mamercad** [comment]
Interesting; is the behavior different with `unique_name: true`?

**Comment by Lvl4Sword** [comment]
This happens specifically if unique_name is true

**Comment by mamercad** [comment]
Hrm, the reason why I asked is because `unique_name: true` isn't set in the example that you're posting. Could you (after redacting anything sensitive), provide the playbook so that I can reproduce this locally?

**Comment by Lvl4Sword** [comment]
Something like the following will trigger it:
```yaml
- name: Create a new Droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    name: "{{ droplet_name }}"
    unique_name: yes
    oauth_token: "{{ do_oauth_token }}"
    size_id: s-1vcpu-2gb
    region_id: nyc1
    image_id: ubuntu-20-04-x64
    ipv6: yes
    monitoring: yes
    ssh_keys: ['Redacted']
    wait_timeout: 300
    tags: ['test']
  register: my_droplet
  ```
