### ISSUE TITLE
Ansible inventory plugin grouping or filtering based on multiple tags

### ISSUE THREAD

**Issue by KingGooseJr** [ansible-collections/community.digitalocean#246]
##### SUMMARY

I would like to group a set of DO droplets based on more than one tag.
For example:

groups:
  somegroup: '"sometag" && "sometag2" in do_tags'

or 

groups:
  somegroup: '"sometag" in do_tags' and '"sometag2" in do_tags'
However, it appears that this syntax is unnacceptable because it does not yield any droplets in the hosts of that group and there should be at least three droplets with both of those tags.  Perhaps I have the syntax wrong and am missing the correct operator or keyword, but this would be helpful here and with the filter keyword.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

digitalocean ansible inventory plugin
##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /home/stephen/ansible_testing/ansible/ansible.cfg
  configured module search path = ['/home/stephen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

ubuntu 20.04 LTS

##### STEPS TO REPRODUCE

Create an inventory file that contains this content

plugin: community.digitalocean.digitalocean
api_token: "{{ lookup( 'env', 'DO_API_TOKEN' ) }}"
attributes:
  - id
  - name
  - tags
  - networks

groups:
  somegroup: '"sometag" && "sometag2" in do_tags'

then run command
ansible-inventory -i inventoryfile.digitalocean.yml --list

```yaml

```

##### EXPECTED RESULTS

Expected the "somegroup" group to have droplets that had both tags "sometag" and "sometag2" within the group and leave all other droplets ungrouped.

##### ACTUAL RESULTS

```paste below
result (if using tags that are available in digitalocean droplets, is that all droplets no matter their tags are returned ungrouped.

```

**Comment by mamercad** [comment]
I think that you can already do this, could you try something like this:

```yaml
plugin: community.digitalocean.digitalocean
api_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
attributes:
  - id
  - name
  - memory
  - vcpus
  - disk
  - size
  - image
  - networks
  - volume_ids
  - tags
  - region
keyed_groups:
  - key: do_region.slug
    prefix: 'region'
    separator: '_'
groups:
  somegroup: "('sometag' in do_tags) and ('sometag2' in do_tags)"
```

Please re-open the issue if it doesn't work.
