### ISSUE TITLE
Add `project_id` or `project_name` as a filter for dynamic inventory

### ISSUE THREAD

**Issue by nirname** [ansible-collections/community.digitalocean#282]
##### SUMMARY

I'd like to split my inventories by `project_name` or `project_id` 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
digitalocean, dynamic inventory module

##### ADDITIONAL INFORMATION

```yaml
plugin: community.digitalocean.digitalocean
attributes:
  - id
  - name
  - networks
  - tags
keyed_groups:
  - key: do_tags | lower
    prefix: ''
    separator: ''
compose:
  ansible_host: do_networks.v4 | selectattr('type','eq','public') | map(attribute='ip_address') | first
filters:
  - 'do_project.name == "sandbox"'
```
