### ISSUE TITLE
Unexpected result during execution of kubernetes module

### ISSUE THREAD

**Issue by raman-babich** [ansible-collections/community.digitalocean#322]
##### SUMMARY

There is unnecessary erasure of resulting data in the [digital_ocean_kubernetes module](https://github.com/ansible-collections/community.digitalocean/blob/main/plugins/modules/digital_ocean_kubernetes.py)

```python
# Add the kubeconfig to the return
if self.return_kubeconfig:
    json_data["kubeconfig"] = self.get_kubernetes_kubeconfig()
self.module.exit_json(changed=True, data=json_data["kubernetes_cluster"])
```
It looks like the last line of the snippet should be.

```python
self.module.exit_json(changed=True, data=json_data)
```
To have kubeconfig correctly included.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

[digital_ocean_kubernetes](https://github.com/ansible-collections/community.digitalocean/blob/main/plugins/modules/digital_ocean_kubernetes.py)

##### ANSIBLE VERSION

```paste below
any
```

##### COLLECTION VERSION

```paste below
1.24.0
```

##### CONFIGURATION

```paste below
Not important
```

##### OS / ENVIRONMENT

Any

##### STEPS TO REPRODUCE

From examples.

```yaml
- name: Create a new DigitalOcean Kubernetes cluster in New York 1
  community.digitalocean.digital_ocean_kubernetes:
    state: present
    oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
    name: hacktoberfest
    region: nyc1
    node_pools:
      - name: hacktoberfest-workers
        size: s-1vcpu-2gb
        count: 3
    return_kubeconfig: true
    wait_timeout: 600
  register: my_cluster
```

##### EXPECTED RESULTS

A kubeconfig is returned.

##### ACTUAL RESULTS

A kubeconfig is not returned.
