### ISSUE TITLE
Ability to deploy droplet from custom image (or snapshot)

### ISSUE THREAD

**Issue by Lusitaniae** [ansible-collections/community.digitalocean#358]
DigitalOcean only provides a few images by default (Ubuntu, Debian, Fedora, Centos, etc)

But they support the optioon to deploy custom images and or deploy from a VM snapshot too which can be very useful in automation

##### SUMMARY
either image_id should accept an integer value and find the respective image, or a new field should be created

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

community.digitalocean.digital_ocean_droplet

##### ADDITIONAL INFORMATION

```yaml
- name: Launch DO
  community.digitalocean.digital_ocean_droplet:
    state: present
    name: "my-app"
    size: "c-2"
    image_id: "4567432"
    region: "nyc1"
```
