### ISSUE TITLE
Allow ``digital_ocean_kubernetes_info`` to return all clusters if the cluster name is not specified

### ISSUE THREAD

**Issue by elcfd** [ansible-collections/community.digitalocean#367]
##### SUMMARY
``digital_ocean_kubernetes_info`` can be improved to follow the ``digital_ocean_droplet_info`` module where if you do not specify a droplet name all the droplets will be returned.

Implement the same for ``digital_ocean_kubernetes_info`` so that if the cluster name is not specified it returns all the clusters

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
``digital_ocean_kubernetes_info``

##### ADDITIONAL INFORMATION
Matches the Digital Ocean [API](https://docs.digitalocean.com/reference/api/api-reference/#operation/kubernetes_list_clusters) and also provides the same functionality as the ``digital_ocean_droplet_info`` module.

```yaml
- name: Gather information about all kubernetes clusters
  community.digitalocean.digital_ocean_kubernetes_info:
    oauth_token: "{{ oauth_token }}"
```
