### ISSUE TITLE
Intentory Plugin does not allow to compose ansible_user

### ISSUE THREAD

**Issue by patriziotomato** [ansible-collections/community.digitalocean#377]
##### SUMMARY

I cannot compose an ansible_user in inventory plugin, but ansible_port works like expected.

```
compose:
  ansible_host: do_networks.v4 | selectattr('type','eq','public')
    | map(attribute='ip_address') | first
  # why is that not working???
#  ansible_user: 'rmts' if 'fw-secured' in do_tags | lower else 'root'
  # Works smoothly
  ansible_port: 2020 if 'fw-secured' in do_tags | lower else '22'
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Inventory Plugin

##### ANSIBLE VERSION

```paste below
ansible-playbook [core 2.13.13]
  config file = /data/resources/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /data/resources/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.10.14 (main, Mar 23 2024, 12:43:01) [GCC 11.2.1 20220219]
  jinja version = 3.1.4
  libyaml = True

```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/data/resources/ansible/ansible.cfg) = ['/data/resources/ansible/collections']
DEFAULT_HOST_LIST(/data/resources/ansible/ansible.cfg) = ['/data/resources/ansible/digitalocean.yml']
DEFAULT_ROLES_PATH(/data/resources/ansible/ansible.cfg) = ['/data/resources/ansible/roles']
DEFAULT_TIMEOUT(/data/resources/ansible/ansible.cfg) = 800
DEPRECATION_WARNINGS(/data/resources/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/data/resources/ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/data/resources/ansible/ansible.cfg) = 800
```

##### STEPS TO REPRODUCE
Please see the example in my summary. I looks like there is no way to specify/compose an ansible_user in the inventory plugin. However, I need to specify a certain user, based on the droplet-tag.

##### EXPECTED RESULTS
Take the ansible_user and set it properly in inventory

##### ACTUAL RESULTS
Is not set in inventory at all
