### ISSUE TITLE
digital_ocean_droplet support resizing

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/community.digitalocean#4]
_From @jaschaio on Dec 13, 2019 12:35_

##### SUMMARY
Similar to #65623 it would be awesome if the `digital_ocean_droplet` module would support resizing of Droplets.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`digital_ocean_droplet`

##### ADDITIONAL INFORMATION
Currently the module only checks if a Droplet exists with the given name. It would be awesome if the module would check additionally if the given droplet has as well the same size as defined in the playbook. If it doesn't it could poweroff the droplet and resize it accordingly.

```yaml
# Resize if droplet exists but block_size is different
-  digital_ocean_droplet:
    state: present
    name: 'example_droplet'
    unique_name: yes # makes it indempotent
    oauth_token: '{{ digitalocean_token }}'
    size: s-1vcpu-1gb # If this value changes, resize the droplet
    region: 'ams3'
    image: ubuntu-18-04-x64
```

_Copied from original issue: ansible/ansible#65806_
