### ISSUE TITLE
Deleting tags is not idempotent

### ISSUE THREAD

**Issue by mamercad** [ansible-collections/community.digitalocean#61]
##### SUMMARY

Deleting tags is not idempotent, the play shows as "changed" when it does not change anything.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

* digital_ocean_tag

##### ANSIBLE VERSION

```paste below
ansible 2.10.8
  config file = /Users/mark/.ansible.cfg
  configured module search path = ['/Users/mark/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mark/.pyenv/versions/3.8.8/lib/python3.8/site-packages/ansible
  executable location = /Users/mark/.pyenv/versions/3.8.8/bin/ansible
  python version = 3.8.8 (default, Apr 12 2021, 20:17:20) [Clang 12.0.0 (clang-1200.0.32.28)]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/Users/mark/.ansible.cfg) = ['timer', 'profile_tasks']
DEFAULT_STDOUT_CALLBACK(/Users/mark/.ansible.cfg) = yaml
DIFF_ALWAYS(/Users/mark/.ansible.cfg) = True
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no

  tasks:

    - name: Delete tag
      community.digitalocean.digital_ocean_tag:
        name: my_tag
        state: absent
      register: delete_tag
```

##### EXPECTED RESULTS

Since the tag doesn't exist (verified), it should not show "changed" when removing it.

##### ACTUAL RESULTS

```paste below
TASK [Delete tag] ***********************************************************************************************************
Saturday 17 April 2021  10:04:28 -0400 (0:00:00.074)       0:00:00.074 ******** 
changed: [localhost] => changed=true

PLAY RECAP ******************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
